version: 2.1
executors:
  arm64-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: arm-medium
  amd64-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

jobs:
  build-arm64:
    executor: arm64-executor
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build Docker Image (ARM64)
          command: |
            docker build -t hello-world-arm64 .
            docker save hello-world-arm64 | gzip > hello-world-arm64.tar.gz

      - store_artifacts:
          path: hello-world-arm64.tar.gz
          destination: docker-artifacts-arm64

  build-amd64:
    executor: amd64-executor
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build Docker Image (AMD64)
          command: |
            docker build -t hello-world-amd64 .
            docker save hello-world-amd64 | gzip > hello-world-amd64.tar.gz

      - store_artifacts:
          path: hello-world-amd64.tar.gz
          destination: docker-artifacts-amd64

  push-multi-arch:
    executor: amd64-executor
    environment:
      ORG: jamesmortensen
      REPO: circle-ci-multi-arch
      VCS_TYPE: github
    steps:
      - checkout

      - run:
          name: Get job ids for required jobs
          command: |
            sh get-workflow.js
            ARM64_JOBID=$(node get-job-id.js build-arm64 | tail -n1 | awk '{print $3}')
            AMD64_JOBID=$(node get-job-id.js build-amd64 | tail -n1 | awk '{print $3}')
            echo 'export ARM64_JOBID='$ARM64_JOBID >> $BASH_ENV
            echo 'export AMD64_JOBID='$AMD64_JOBID >> $BASH_ENV

      - run:
          name: Download artifacts
          command: |
            #curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/$VCS_TYPE/$ORG/$REPO/latest/artifacts
            curl --request GET \
              --url https://circleci.com/api/v2/project/gh/$ORG/$REPO/$ARM64_JOBID/artifacts \
              --header "Circle-Token: $CIRCLE_TOKEN" > artifact-arm64.json
            curl --request GET \
              --url https://circleci.com/api/v2/project/gh/$ORG/$REPO/$AMD64_JOBID/artifacts \
              --header "Circle-Token: $CIRCLE_TOKEN" > artifact-amd64.json
            curl -L $(node get-artifact-url.js artifact-arm64.json | tail -n1) --output docker-artifacts-arm64.tar.gz
            curl -L $(node get-artifact-url.js artifact-amd64.json | tail -n1) --output docker-artifacts-amd64.tar.gz

      - run:
          name: Install Docker Buildx
          command: |
            docker buildx create --use
      - run:
          name: Load ARM64 Image
          command: |
            docker load < docker-artifacts-arm64.tar.gz
            docker load < docker-artifacts-amd64.tar.gz
      - run:
          name: Push Multi-Arch Image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN
            docker buildx build --platform linux/amd64,linux/arm64 -t jamesmortensen1/hello-world --push .

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-arm64
      - build-amd64
      - push-multi-arch:
          requires:
            - build-arm64
            - build-amd64

